services:
  twitch-chat:
    volumes:
      - ./packages/twitch/chat/src:/app/packages/twitch/chat/src

  twitch-events:
    volumes:
      - ./packages/twitch/events/src:/app/packages/twitch/events/src

  dota:
    volumes:
      - ./packages/dota/src:/app/packages/dota/src
      - ./packages/dota/jest.config.ts:/app/packages/dota/jest.config.ts

  nginx:
    profiles:
      - donotstart

  mongodb:
    container_name: mongodb
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
      - ./services/mongodb/src/init.js:/docker-entrypoint-initdb.d/init_mongo.js
