services:
  twitch-chat:
    image: "ghcr.io/dotabod/twitch-chat:v2.0-dev"
    volumes:
      - $CWD/packages/twitch/chat/src/:/app/packages/twitch/chat/src/

  steam:
    image: "ghcr.io/dotabod/steam:v2.0-dev"
    volumes:
      - $CWD/packages/steam/src:/app/packages/steam/src

  twitch-events:
    image: "ghcr.io/dotabod/twitch-events:v2.0-dev"
    volumes:
      - $CWD/packages/twitch/events/src:/app/packages/twitch/events/src

  dota:
    image: "ghcr.io/dotabod/dota:v2.0-dev"
    volumes:
      - $CWD/packages/dota/src:/app/packages/dota/src
      - $CWD/packages/dota/jest.config.ts:/app/packages/dota/jest.config.ts
    ports:
      - "5120:5120"

  nginx:
    profiles:
      - donotstart

  mongodb:
    container_name: mongodb
    image: "mongo:latest"
    volumes:
      - "mongodb_data:/data/db"
      - $CWD/services/mongodb/src/init.js:/docker-entrypoint-initdb.d/init_mongo.js
