services:
  twitch-chat:
    image: "ghcr.io/dotabod/twitch-chat:v1.0"
    volumes:
      - ./packages/twitch/chat/src:/app/packages/twitch/chat/src

  twitch-events:
    image: "ghcr.io/dotabod/twitch-events:v1.0"
    volumes:
      - ./packages/twitch/events/src:/app/packages/twitch/events/src

  dota:
    image: "ghcr.io/dotabod/dota:v1.0"
    volumes:
      - ./packages/dota/src:/app/packages/dota/src

  nginx:
    profiles:
      - donotstart

  mongodb:
    container_name: mongodb
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
      - ./services/mongodb/src/init.js:/docker-entrypoint-initdb.d/init_mongo.js
