services:
  redis:
    container_name: redis
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"

  twitch-chat:
    image: "ghcr.io/dotabod/twitch-chat:latest"
    container_name: twitch-chat
    restart: on-failure
    build:
      context: .
      dockerfile: ./packages/Dockerfile.chat
      args:
        - BUILD_CONTEXT=packages/twitch/chat
    hostname: twitch-chat
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URL
      - DB_SECRET
      - DB_URL
      - DEV_CHANNELS
      - DEV_CHANNELIDS
      - MONGO_URL
      - NODE_ENV
      - TWITCH_BOT_PROVIDERID
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
    volumes:
      - ./packages/twitch/chat/locales:/app/packages/twitch/chat/locales

  twitch-events:
    image: "ghcr.io/dotabod/twitch-events:latest"
    container_name: twitch-events
    restart: on-failure
    build:
      context: .
      dockerfile: ./packages/Dockerfile.events
      args:
        - BUILD_CONTEXT=packages/twitch/events
    hostname: twitch-events
    ports:
      - "82:5010"
      - "5015:5015"
      - "5011:5011"
    environment:
      - DATABASE_URL
      - DB_SECRET
      - DB_URL
      - DEV_CHANNELS
      - DEV_CHANNELIDS
      - EVENTSUB_HOST
      - HOOKS_HOST
      - MONGO_URL
      - NODE_ENV
      - PORT=5010
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - TWITCH_EVENTSUB_SECRET

  dota:
    image: "ghcr.io/dotabod/dota:latest"
    container_name: dota
    restart: on-failure
    build:
      context: .
      dockerfile: ./packages/Dockerfile.dota
      args:
        - BUILD_CONTEXT=packages/dota
    hostname: dota
    ports:
      - "81:5000"
      - "9229:9229"
    environment:
      - D2PT_TOKEN
      - ADMIN_CHANNELS
      - COMMIT_HASH
      - DATABASE_URL
      - DB_SECRET
      - DB_URL
      - DEV_CHANNELS
      - DEV_CHANNELIDS
      - MONGO_URL
      - NODE_ENV
      - STEAM_PASS
      - STEAM_USER
      - STEAM_WEB_API
      - TWITCH_BOT_PROVIDERID
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
    volumes:
      # Storing locales in a volume so that they can be edited without rebuilding the image
      - ./packages/dota/locales:/app/packages/dota/locales
      - steam_auth:/app/packages/dota/src/steam/volumes

  nginx:
    container_name: nginx
    restart: on-failure
    image: "nginx:latest"
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/templates/default.conf.template
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST
      - EVENTSUB_HOST
      - HOOKS_HOST
      - TLS_CERT
      - TLS_KEY

# Volumes are useful for data persistence, so the data will not be deleted
# even later you call command docker-compose down.
volumes:
  mongodb_data:
  steam_auth:
networks:
  default:
    name: dotabod
